consentModal:
  title: Information som vi samlar
  description: >
    Här kan du se och anpassa vilken information vi samlar om dig.
  privacyPolicy:
    name: Integritetspolicy
    text: >
      För att veta mer, läs vår {privacyPolicy}.
consentNotice:
  changeDescription: Det har skett förändringar sedan ditt senaste besök, var god uppdatera ditt medgivande.
  description: >
    Vi samlar och bearbetar din personliga data i följande syften: {purposes}.
learnMore: 'Läs mer'
Accept Cookies: Godkänn Cookies
Cookie text 1: 'Insida använder ett antal typer av kakor för webbplatsen, dessa kakor är:'
Cookie text 2: '- kakor som vi måste ha för att webbplatsen ska fungera korrekt och våra tjänster inte ska missbrukas.'
Cookie text 2 heading: 'Nödvändiga kakor'
Cookie text 3: '- dessa kakor samlar in information om dig och hur du använder webbplatsen för att skapa en bättre upplevelse.'
Cookie text 3 heading: 'Funktionalitets kakor'
Cookie text 4: '- är kakor som används för att ge mer relevanta annonser till dig.'
Cookie text 4 heading: 'Annonserings kakor'
save: Spara
Cookie Preferences: Dina val av kakor
Cookie Settings: Cookie-Inställningar
app:
  disableAll:
    title: Ändra för alla appar
    description: Använd detta reglage för att aktivera/avaktivera samtliga appar.
  optOut:
    title: (Avaktivera)
    description: Den här appen laddas som standardinställning (men du kan avaktivera den)
  required:
    title: (Krävs alltid)
    description: Den här applikationen krävs alltid
  purposes: Syften
  purpose: Syfte
poweredBy: Inosidas kak fabrik
